version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: samba_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Plmdd198219$
      POSTGRES_DB: samba_simulator
    ports:
      - "5433:5432"
    volumes:
      - samba_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: samba_api
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - storage:/app/storage
    restart: unless-stopped

volumes:
  samba_pg_data:
  storage: