"""add created_at to users

Revision ID: 6cf7a40b4447
Revises: f27c5666bd61
Create Date: 2026-02-26 00:16:02.118345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cf7a40b4447'
down_revision: Union[str, None] = 'f27c5666bd61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blueprints')
    op.alter_column('disciplines', 'name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.drop_constraint('disciplines_name_key', 'disciplines', type_='unique')
    op.create_index(op.f('ix_disciplines_name'), 'disciplines', ['name'], unique=True)
    op.add_column('items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('items', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('items', 'serie',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('items', 'latex',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_items_serie'), 'items', ['serie'], unique=False)
    op.drop_constraint('items_skill_id_fkey', 'items', type_='foreignkey')
    op.drop_constraint('items_owner_id_fkey', 'items', type_='foreignkey')
    op.drop_constraint('items_discipline_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'items', 'skills', ['skill_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'items', 'disciplines', ['discipline_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.add_column('skills', sa.Column('discipline_id', sa.Integer(), nullable=False))
    op.alter_column('skills', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_foreign_key(None, 'skills', 'disciplines', ['discipline_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_roles_user_id_fkey', 'user_roles', type_='foreignkey')
    op.drop_constraint('user_roles_role_id_fkey', 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key('user_roles_role_id_fkey', 'user_roles', 'roles', ['role_id'], ['id'])
    op.create_foreign_key('user_roles_user_id_fkey', 'user_roles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.alter_column('skills', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('skills', 'discipline_id')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_discipline_id_fkey', 'items', 'disciplines', ['discipline_id'], ['id'])
    op.create_foreign_key('items_owner_id_fkey', 'items', 'users', ['owner_id'], ['id'])
    op.create_foreign_key('items_skill_id_fkey', 'items', 'skills', ['skill_id'], ['id'])
    op.drop_index(op.f('ix_items_serie'), table_name='items')
    op.alter_column('items', 'latex',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('items', 'serie',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('items', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('items', 'created_at')
    op.drop_index(op.f('ix_disciplines_name'), table_name='disciplines')
    op.create_unique_constraint('disciplines_name_key', 'disciplines', ['name'])
    op.alter_column('disciplines', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.create_table('blueprints',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='blueprints_pkey')
    )
    # ### end Alembic commands ###
