"""add blueprint model

Revision ID: a537dc3c12e6
Revises: 81c2c32fdd74
Create Date: 2026-02-22 18:23:09.311408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a537dc3c12e6'
down_revision: Union[str, None] = '81c2c32fdd74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blueprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('assessment_configs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('bimestre', postgresql.ENUM('b1', 'b2', 'b3', 'b4', name='bimesterenum'), autoincrement=False, nullable=False),
    sa.Column('area', postgresql.ENUM('linguagens', 'mat', 'cn', 'ch', name='areaconhecimentoenum'), autoincrement=False, nullable=False),
    sa.Column('serie', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('total_questoes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='assessment_configs_pkey'),
    sa.UniqueConstraint('bimestre', 'area', 'serie', name='uq_assessment_config_bim_area_serie')
    )
    op.drop_table('blueprints')
    # ### end Alembic commands ###
