"""init

Revision ID: e074af2d6c2d
Revises: 
Create Date: 2026-02-21 01:49:27.026411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e074af2d6c2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('bimestre', sa.Enum('b1', 'b2', 'b3', 'b4', name='bimesterenum'), nullable=False),
    sa.Column('area', sa.Enum('linguagens', 'mat', 'cn', 'ch', name='areaconhecimentoenum'), nullable=False),
    sa.Column('serie', sa.String(length=10), nullable=False),
    sa.Column('total_questoes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bimestre', 'area', 'serie', name='uq_assessment_config_bim_area_serie')
    )
    op.create_table('disciplines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_code'), 'skills', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('COORDINATOR', 'TEACHER', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('serie', sa.String(length=10), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficultyenum'), nullable=False),
    sa.Column('item_type', sa.Enum('mcq', 'numeric', 'open', name='itemtypeenum'), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=True),
    sa.Column('numeric_answer', sa.String(length=50), nullable=True),
    sa.Column('media_url', sa.String(length=255), nullable=True),
    sa.Column('latex', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_code'), table_name='skills')
    op.drop_table('skills')
    op.drop_table('disciplines')
    op.drop_table('assessment_configs')
    # ### end Alembic commands ###
