"""school structure (grades/sections/classes)

Revision ID: f27c5666bd61
Revises: 423e3074d76d
Create Date: 2026-02-23 01:28:45.871905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f27c5666bd61'
down_revision: Union[str, None] = '423e3074d76d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_sections_label'), 'class_sections', ['label'], unique=True)
    op.create_table('school_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('FUNDAMENTAL', 'MEDIO', name='educationlevel'), nullable=False),
    sa.Column('year_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level', 'year_number', name='uq_grade_level_year')
    )
    op.create_index(op.f('ix_school_grades_level'), 'school_grades', ['level'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('area', sa.String(length=80), nullable=True),
    sa.Column('options_count', sa.Integer(), nullable=False),
    sa.Column('answer_source', sa.Enum('TEACHERS', 'COORDINATOR_OMR', name='answersource'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'COLLECTING', 'REVIEW', 'LOCKED', 'GENERATED', 'PUBLISHED', name='examstatus'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['school_grades.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['class_sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade_id', 'section_id', name='uq_class_grade_section')
    )
    op.create_index('ix_class_name', 'school_classes', ['name'], unique=False)
    op.create_index(op.f('ix_school_classes_grade_id'), 'school_classes', ['grade_id'], unique=False)
    op.create_index(op.f('ix_school_classes_section_id'), 'school_classes', ['section_id'], unique=False)
    op.create_table('exam_class_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'class_id', name='uq_exam_class')
    )
    op.create_index(op.f('ix_exam_class_assignment_class_id'), 'exam_class_assignment', ['class_id'], unique=False)
    op.create_index(op.f('ix_exam_class_assignment_exam_id'), 'exam_class_assignment', ['exam_id'], unique=False)
    op.create_table('exam_discipline_quota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('quota', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'discipline_id', name='uq_exam_quota')
    )
    op.create_index(op.f('ix_exam_discipline_quota_discipline_id'), 'exam_discipline_quota', ['discipline_id'], unique=False)
    op.create_index(op.f('ix_exam_discipline_quota_exam_id'), 'exam_discipline_quota', ['exam_id'], unique=False)
    op.create_table('exam_teacher_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('teacher_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'class_id', 'discipline_id', 'teacher_user_id', name='uq_exam_teacher_slot')
    )
    op.create_index(op.f('ix_exam_teacher_assignment_class_id'), 'exam_teacher_assignment', ['class_id'], unique=False)
    op.create_index(op.f('ix_exam_teacher_assignment_discipline_id'), 'exam_teacher_assignment', ['discipline_id'], unique=False)
    op.create_index(op.f('ix_exam_teacher_assignment_exam_id'), 'exam_teacher_assignment', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_teacher_assignment_teacher_user_id'), 'exam_teacher_assignment', ['teacher_user_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'PASTE', 'TXT', 'DOCX', name='questionsource'), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', name='questionstate'), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('has_images', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_author_user_id'), 'questions', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_questions_class_id'), 'questions', ['class_id'], unique=False)
    op.create_index(op.f('ix_questions_discipline_id'), 'questions', ['discipline_id'], unique=False)
    op.create_index(op.f('ix_questions_exam_id'), 'questions', ['exam_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ra', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_class_id'), 'students', ['class_id'], unique=False)
    op.create_index(op.f('ix_students_ra'), 'students', ['ra'], unique=True)
    op.create_table('teacher_class_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_user_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_user_id', 'class_id', 'discipline_id', name='uq_teacher_class_subject')
    )
    op.create_index(op.f('ix_teacher_class_subject_class_id'), 'teacher_class_subject', ['class_id'], unique=False)
    op.create_index(op.f('ix_teacher_class_subject_discipline_id'), 'teacher_class_subject', ['discipline_id'], unique=False)
    op.create_index(op.f('ix_teacher_class_subject_teacher_user_id'), 'teacher_class_subject', ['teacher_user_id'], unique=False)
    op.create_table('exam_question_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('order_idx', sa.Integer(), nullable=False),
    sa.Column('correct_label', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'order_idx', name='uq_exam_order_idx'),
    sa.UniqueConstraint('exam_id', 'question_id', name='uq_exam_question_once')
    )
    op.create_index(op.f('ix_exam_question_link_exam_id'), 'exam_question_link', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_question_link_question_id'), 'exam_question_link', ['question_id'], unique=False)
    op.create_index('ix_exam_question_order', 'exam_question_link', ['exam_id', 'order_idx'], unique=False)
    op.create_table('question_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=1), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'label', name='uq_question_option_label')
    )
    op.create_index(op.f('ix_question_options_question_id'), 'question_options', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_options_question_id'), table_name='question_options')
    op.drop_table('question_options')
    op.drop_index('ix_exam_question_order', table_name='exam_question_link')
    op.drop_index(op.f('ix_exam_question_link_question_id'), table_name='exam_question_link')
    op.drop_index(op.f('ix_exam_question_link_exam_id'), table_name='exam_question_link')
    op.drop_table('exam_question_link')
    op.drop_index(op.f('ix_teacher_class_subject_teacher_user_id'), table_name='teacher_class_subject')
    op.drop_index(op.f('ix_teacher_class_subject_discipline_id'), table_name='teacher_class_subject')
    op.drop_index(op.f('ix_teacher_class_subject_class_id'), table_name='teacher_class_subject')
    op.drop_table('teacher_class_subject')
    op.drop_index(op.f('ix_students_ra'), table_name='students')
    op.drop_index(op.f('ix_students_class_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_questions_exam_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_discipline_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_class_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_author_user_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_exam_teacher_assignment_teacher_user_id'), table_name='exam_teacher_assignment')
    op.drop_index(op.f('ix_exam_teacher_assignment_exam_id'), table_name='exam_teacher_assignment')
    op.drop_index(op.f('ix_exam_teacher_assignment_discipline_id'), table_name='exam_teacher_assignment')
    op.drop_index(op.f('ix_exam_teacher_assignment_class_id'), table_name='exam_teacher_assignment')
    op.drop_table('exam_teacher_assignment')
    op.drop_index(op.f('ix_exam_discipline_quota_exam_id'), table_name='exam_discipline_quota')
    op.drop_index(op.f('ix_exam_discipline_quota_discipline_id'), table_name='exam_discipline_quota')
    op.drop_table('exam_discipline_quota')
    op.drop_index(op.f('ix_exam_class_assignment_exam_id'), table_name='exam_class_assignment')
    op.drop_index(op.f('ix_exam_class_assignment_class_id'), table_name='exam_class_assignment')
    op.drop_table('exam_class_assignment')
    op.drop_index(op.f('ix_school_classes_section_id'), table_name='school_classes')
    op.drop_index(op.f('ix_school_classes_grade_id'), table_name='school_classes')
    op.drop_index('ix_class_name', table_name='school_classes')
    op.drop_table('school_classes')
    op.drop_table('exams')
    op.drop_index(op.f('ix_school_grades_level'), table_name='school_grades')
    op.drop_table('school_grades')
    op.drop_index(op.f('ix_class_sections_label'), table_name='class_sections')
    op.drop_table('class_sections')
    # ### end Alembic commands ###
